class MoveError(Exception):
    pass

class AttackError(Exception):
    pass
